import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";

import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";
import { PropsWithChildren } from "react";
import QueryClProvider from "./QueryClProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import AuthProvider from "./dashboard/auth/AuthProvider";
import { ThemeProvider } from "./providers/ThemeProvider"; // Your provider

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clinical App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    // Add suppressHydrationWarning to the html tag
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Theme accentColor="violet" radius="medium" appearance="inherit">
              <QueryClProvider>
                <Container>
                  <header>
                    <NavBar />
                  </header>
                  <main className="py-5">{children}</main>
                </Container>
                <ReactQueryDevtools initialIsOpen={false} />
              </QueryClProvider>
            </Theme>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
